name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build and test with Gradle
        run: ./gradlew build test

      - name: Run Debug Test
        run: ./gradlew testDebugUnitTest --continue
      - name: Upload Test Reports
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
            name: test-reports
            path: '**/build/reports/test/'



